name: e9337e67-37ad-4c6d-9fd8-700abb3448ca
displayName: ChainStorage API
type: restapi
environment: production
host: null
port: null
databaseName: null
databaseUsername: null
databasePassword: null
ssl: null
editPrivilege: null
options:
  baseURL: >-
    https://chainstorage-ethereum-mainnet-http-dev.cbhq.net/coinbase.chainstorage.ChainStorage
  headers:
    - - Content-Type
      - application/json
  urlparams:
    - - ''
      - ''
  auth0_domain: ''
  oauth2_scope: ''
  auth0_clientID: ''
  authentication: ''
  basic_password: ''
  basic_username: ''
  oauth2_auth_url: ''
  cookiesToForward: []
  oauth2_client_id: ''
  forwardAllCookies: false
  auth0_clientSecret: ''
  extraBodyKeyValues:
    - - ''
      - ''
  verify_session_url: ''
  oauth2_access_token: ''
  oauth2_callback_url: http://localhost:3001/oauth/user/oauthcallback
  session_cookie_name: ''
  oauth2_client_secret: ''
  oauth2_refresh_token: ''
  auth0_custom_audience: ''
  oauth1_signature_method: HMAC-SHA1
  oauth2_access_token_url: ''
dynamicallyQueryable: false
createdAt: 2021-11-03T15:43:06.905Z
updatedAt: 2021-11-03T16:14:05.931Z
version: '1.0'
